name: MyBiasLevelUp
options:
  minimumXcodeGenVersion: 2.44.1
settings:
  base:
    SWIFT_VERSION: 6.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
configs:
  Debug: debug
  Release: release
targets:
  MyBiasLevelUp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Features
      - path: Domain
      - path: Data
      - path: Resources/Data/characters.json
        type: file
        buildPhase: resources
      - path: Resources/Data/weapons.json
        type: file
        buildPhase: resources
      - path: Resources/Data/schedules.json
        type: file
        buildPhase: resources
      - path: Resources/Images
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mybiaslevelup.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: MyBiasLevelUp
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets:
        - MyBiasLevelUpTests
        - MyBiasLevelUpUITests
  MyBiasLevelUpTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests/Unit
    dependencies:
      - target: MyBiasLevelUp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mybiaslevelup.tests
        GENERATE_INFOPLIST_FILE: YES
  MyBiasLevelUpUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests/UI
    dependencies:
      - target: MyBiasLevelUp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mybiaslevelup.uitests
        GENERATE_INFOPLIST_FILE: YES
